common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', views.custom_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mainApp.urls')),
    path('questions/', include('questions.urls')),
    path('common/', include('common.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('<int:question_id>/', views.question_detail, name='question_detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('result/', views.result, name='result'),
    path('recommendation/', views.get_tourist_data, name='recommendation'),
]

yeogi_chucheon_project/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mainApp.urls')),
    path('questions/', include('questions.urls')),
    path('common/', include('common.urls')),
]

questions/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

questions/views.py
from django.shortcuts import render, redirect

# 모델
from .models import Question, Choice
from .api_tour import tourist_printout
from .api_openai_dalle import create_img
from .deep_learning_module import predict_destination
# 외부 라이브러리
import requests


def question_detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        return render(request, 'questions/error.html', {'error_message': "Question not found."})

    question_count = Question.objects.count()
    return render(request, 'questions/question_detail.html', {'question': question, 'question_count': question_count})


def vote(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        return render(request, 'questions/error.html', {'error_message': "Question not found."})

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'questions/question_detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        if 'selected_choices' not in request.session:
            request.session['selected_choices'] = {}

        selected_choices = request.session['selected_choices']
        selected_choices[question_id] = selected_choice.id
        request.session['selected_choices'] = selected_choices

        # Find the next valid question ID
        next_question_id = question_id + 1
        question_count = 1
        total_questions = Question.objects.count()

        while question_count <= total_questions:
            if Question.objects.filter(pk=next_question_id).exists():

                return redirect('questions:question_detail', question_id=next_question_id)
            next_question_id += 1
            question_count += 1

        # If all questions are answered, go to result page
        return redirect('questions:result')



def result(request):
    selected_choices = request.session.get('selected_choices', {})
    selected_choices_list = []

    if not selected_choices:
        # 세션에 선택된 데이터가 없으면 에러 메시지 추가
        return render(request, 'questions/result.html', {'error_message': "No choices have been made."})

    for question_id, choice_id in selected_choices.items():
        try:
            question = Question.objects.get(pk=question_id)
            choice = question.choice_set.get(pk=choice_id)
            selected_choices_list.append((question, choice))
        except (Question.DoesNotExist, Choice.DoesNotExist):
            continue  # 해당 질문 또는 선택지가 없는 경우 무시

    if not selected_choices_list:
        return render(request, 'questions/error.html', {'error_message': "No valid choices found."})

    return render(request, 'questions/result.html', {'selected_choices': selected_choices_list})


def get_tourist_data(request):
    prompt = "A fantasy ruins"
    items = tourist_printout()
    ai_image = create_img(prompt)
    context = {'items': items, 'ai_image': ai_image}
    try:

        return render(request, 'questions/recommendation.html', context)

    except requests.exceptions.RequestException as e:

        return render(request, 'questions/recommendation.html', {'message': str(e)})


def result_view(request):
    selected_choices = request.session.get('selected_choices', {})
    selected_choices_list = []

    if not selected_choices:
        return render(request, 'questions/result.html', {'error_message': "No choices have been made."})

    for question_id, choice_id in selected_choices.items():
        try:
            question = Question.objects.get(pk=question_id)
            choice = question.choice_set.get(pk=choice_id)
            selected_choices_list.append((question, choice))
        except (Question.DoesNotExist, Choice.DoesNotExist):
            continue

    if not selected_choices_list:
        return render(request, 'questions/error.html', {'error_message': "No valid choices found."})

    # 여행지 예측을 위한 데이터 준비
    question_texts = [q.question_text for q, _ in selected_choices_list]
    choice_ids = [c.id for _, c in selected_choices_list]

    # 딥러닝 모델을 사용하여 여행지 추천
    recommended_destination = predict_destination(question_texts, choice_ids)

    context = {
        'selected_choices': selected_choices_list,
        'recommended_destination': recommended_destination
    }
    return render(request, 'questions/result.html', context)

templates/questions/area.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Air Pollution Data</h1>
    <ul>
        {% for item in items %}
        <div>
            <img src="{{ item.firstimage }}">
        </div>
        <li>{{ item.title }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/questions/error.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h1>Error</h1>
        <p>{{ error_message }}</p>
        <a href="{% url 'questions:question_detail' question_id=1 %}" class="btn btn-primary">Go to First Question</a>
    </div>
{% endblock %}

templates/questions/question_detail.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'questions/css/styles.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-5">{{ question.question_text }}</h1>
    <form action="{% url 'questions:vote' question.id %}" method="post" class="mt-4">
        {% csrf_token %}
        <div class="choice-container">
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" class="form-check-input">
                <label for="choice{{ forloop.counter }}" class="form-check-label">{{ choice.choice_text }}</label>
            {% empty %}
                <div class="list-group-item">이 질문에 대한 선택사항이 없습니다.</div>
            {% endfor %}
        </div>
        <div class="button-container">
            <button type="submit" class="btn btn-primary">투표하기</button>
        </div>
    </form>
    <div class="button-container">
        {% if question.id > 1 %}
            <a href="{% url 'questions:question_detail' question.id|add:-1 %}" class="btn btn-secondary">이전</a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/questions/recommendation.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'questions/css/styles.css' %}">
{% endblock %}

{% block content %}
<div class="container">
<h1>당신의 여행 성향은?</h1>
<h2>{result}</h2>
    <h3>이상적인 여행지</h3>
    <div>
        <img src="{{ ai_image }}">
    </div>
    <ul>
        {% for item in items %}
        <div>
            <img src="{{ item.firstimage }}">
        </div>
        <li>{{ item.title }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/questions/result.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'questions/css/styles.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1>결과</h1>
    <ul class="custom-list">
        {% for question, choice in selected_choices %}
            <li>{{ question.question_text }}: {{ choice.choice_text }}</li>
        {% endfor %}
    </ul>

    {% if recommended_destination %}
        <h2>추천 여행지: {{ recommended_destination }}</h2>
    {% else %}
        <p>추천 결과를 가져오는 데 문제가 발생했습니다.</p>
    {% endif %}

    <div class="button-container">
        <a href="{% url 'questions:recommendation' %}" class="btn btn-secondary">추천 결과 보기</a>
    </div>
</div>
{% endblock %}