common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', views.custom_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mainApp.urls')),
    path('questions/', include('questions.urls')),
    path('common/', include('common.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.urls import path
from . import views

app_name = 'mainApp'

urlpatterns = [
    path('', views.main_home, name='main_home'),
    path('chatbot/', views.chatbot_view, name='chatbot_view'),
    path('destinations/', views.destinations, name='destinations'),
]

yeogi_chucheon_project/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mainApp.urls')),
    path('questions/', include('questions.urls')),
    path('common/', include('common.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <!-- 추가 CSS -->
    {% block extra_css %}
    {% endblock %}
    <title>여기추천 -MBTI 여행추천-</title>
    <link rel="icon" href="{% static 'mainApp/images/favicon.png' %}" type="image/x-icon">
</head>

<body class="{% block body_class %}{% endblock %}">

<!-- 네비게이션바 -->
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<footer class="footer">
        <div class="logo">
            <img src="{% static 'mainApp/images/logo.png' %}" alt="Travel Site Logo">
        </div>
        <p>&copy; 2024 Travel Site. All rights reserved.</p>
</footer>
<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'mainApp:main_home' %}">여기추천</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                <li>
                    <a class="nav-link" href="{% url 'mainApp:chatbot_view' %}">챗봇 대화</a>
                </li>

            </ul>
        </div>
    </div>
</nav>